version: '3'

services:
  tomahawk.client.angular:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  tomahawk.service.products:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

